---
- name: "get tiller-deploy pod name"
  shell: >
    kubectl get pods --namespace=kube-system |
    grep tiller-deploy- |
    awk '{print $1;}' |
    tr -d '\n'
  register: get_pod_name

- name: "wait for tiller-deploy ready status"
  command: >
    kubectl get pods --namespace=kube-system {{get_pod_name.stdout}}
    -o jsonpath='{.status.containerStatuses[*].ready}'
  register: tiller_ready_status
  # Wait for 10 minutes
  until: tiller_ready_status.stdout | match( '^(true\s)*true$' )
  retries: 20
  delay: 30

- name: Clone OpenFaas repo
  git:
    repo: 'https://github.com/openfaas/faas-netes'
    dest: /tmp/faas-netes
    version: {{ faas_version }}

- name: "Create OpenFaas namespaces"
  command: kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

- name: "Add OpenFaas using Helm"
  command: kubectl apply -f ./yaml
  args:
    chdir: /tmp/faas-netes

- name: "Download the CLI installer"
  get_url:
    url: https://raw.githubusercontent.com/openfaas/faas-cli/{{ cli_version }}/get.sh
    dest: /tmp/faas-cli.sh
    mode: 0755

- name: "Install faas-cli"
  script: /tmp/faas-cli.sh
  
- name: "Add OpenFaas URL to FaasCli"
  lineinfile: 
    path: /etc/environment
    line: OPENFAAS_URL=127.0.0.1:31112