---
- name: "get tiller-deploy pod name"
  shell: >
    kubectl get pods --namespace=kube-system |
    grep tiller-deploy- |
    awk '{print $1;}' |
    tr -d '\n'
  register: get_pod_name

- name: "wait for tiller-deploy ready status"
  command: >
    kubectl get pods --namespace=kube-system {{get_pod_name.stdout}}
    -o jsonpath='{.status.containerStatuses[*].ready}'
  register: tiller_ready_status
  # Wait for 10 minutes
  until: tiller_ready_status.stdout | match( '^(true\s)*true$' )
  retries: 120
  delay: 5

- name: Clone OpenFaas repo
  git:
    repo: 'https://github.com/openfaas/faas-netes'
    dest: /tmp/faas-netes

- name: "Create OpenFaas namespaces"
  command: kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

- name: "Add OpenFaas using Helm"
  command: cd /tmp/faas-netes && kubectl apply -f ./yaml

- name: "Install the CLI"
  command: curl -sL https://cli.openfaas.com | sh